immersive-web/homepage

index.html

Adding teleconference link for immersive-web/homepage issue #2

Added teleconferences link (for issue #2)

---

index.html

for immersive-web/homepage issue #4 
- Added FTF as one section where TPAC 2018 was at
- Moved TPAC 2018 as past
- Added upcoming 2019/Jan FTF

Moved TPAC 2018 as past, added 2019/Jan FTF

---

index.html

Added links to RSVP and CfT

---

index.html

Added FPWD and github issue page to webxr device api line (at sidebar)

---

index.html

(To be merged after F2F finished)

added minutes for June F2F, TPAC 2019

---

index.html

updated to add a link to agenda, also updated TPAC website with this link.

added a link to agenda page of TPAC 2019 in administrivia repo

---

index.html

added issued newsletter at 2019/May/08

Added issued newsletter

---

index.html

Added as announcement to mail list.

added 2020/Feb/5-6 as announced

---

index.html

updated link to Core, added two FPWDs

---

index.html

added DOM-Overlay and hit-test

---

CSS/main.css

bullets from ul > li in header part might be better to be removed? (same for left side panel??)

removed bullets on header

---

README.md
index.html

for https://github.com/immersive-web/webxr-hand-input/issues/33

added WebXR Hand Input

---

index.html

forgot to add when publishing FPWD, sorry.

added TR links to hand-input and layers

---

list_spec.json

webxr-lighting-estimation-1 FPWD published

---

index.html

list f2f meetings

---

index.html

added links to 2022/04 f2f minutes

---

index.html
list_spec.json

WebXR Device API published as CRS

---

index.html

for recharter (and Dominique was still listed as team contact)

updated charter link and team contact

---

index.html
list_spec.json

co-chair reappointment, two TAG HR

updated with 2022/Sep/07 delta

---

index.html

move TPAC 2022 as past and added minutes

---

index.html

updated per https://github.com/immersive-web/homepage/pull/50#issuecomment-1274240445
(should mention about editors?)
/cc @AdaRoseCannon

added chairs list

---

list_spec.json

added tag review on WebXR Device API XRSession::enabledFeatures

---

list_spec.js

mostly for my personal usage (to find editors' names easily at one page for e.g. mass updates), adding some information from specref database.
if you feel adding these are ok, please approve this @Yonet @AdaRoseCannon

get latest links and editors from specref

---

list_spec.json

updates by 2022/12

---

index.html

check at [htmlpreview](https://htmlpreview.github.io/?https://raw.githubusercontent.com/himorin/immersive-web-homepage/f2f-202304/index.html)

added 2023/04 F2F line

---

index.html

for upcoming f2f meeting.
@cabanier do we have some page to be linked for venue?
searching around, [meta careers](https://www.metacareers.com/v2/locations/bellevue/?p[offices][0]=Bellevue%2C%20WA&offices[0]=Bellevue%2C%20WA) does not have address, [BDA](https://www.bellevuedowntown.com/go/meta) seems different building.

F2f 202403

---

index.html

As title. (I believe list is complete...)

Add TPAC 2024 calendars

---

index.html

Moved TPAC 2024 to past, with minutes

---

index.html

as title, will add more once pages or details secured.

Added RSVP for 2025-03 F2F

---

index.html

- updated charter link
- moved 2025/03 f2f item into past f2f, with adding links for agenda and minutes

fixed link, moved 2025/03 f2f to past
